kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: listener-db-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client
  volumeMode: Filesystem